---
title: "satRday_pkg_dev"
author: "Hanjo Odendaal"
date: "16 March 2018"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
library(quotidieR)

load_pkg(c("devtools", "usethis", "testthat", "readr"))
knitr::opts_chunk$set(echo = TRUE)
```

## Questions

- CRAN
- Multiple functions in one .R

## Workflow
```{r}
use_package_doc()
use_testthat()

use_r()
use_package(package = "praise")
use_test("SomeFun.R")
document()



```


## First step

```{r}
edit_r_profile()

create_package("iemand")

# edit description

# Lets add a license to the package directory
use_mit_license(name = "Hanjo Odendaal")

use_r(name = "create_age")

#load the new function to test
load_all()  
```

# Documentation

```{r}
# Insert Roxygen skeleton
Ctrl+Shift+Alt+R

document()

use_package_doc()
```

# Build

```{r}
Ctrl+Shift+B
```

# Git configuration

```{r}
use_git_config(user.name = "HanjoStudy", project = "satrday_pkg_dev")

git2r::config()

use_git()

```

# Unit test

```{r}
use_testthat()

use_test("create_age.R")

Ctrl+Shift+T
```

# Dependencies

```{r}
use_r("praise_nicely")
use_r("xx")

praise_nicely("Hanjo")

use_test("praise_nicely.R")

use_package(package = "praise")
use_package(package = "magrittr")
load_all()
document()
```

# Data

```{r}
# Read in baby names for SA
boy_names <- read_csv("https://raw.githubusercontent.com/maelle/za_babynames/master/data-raw/boys_names.csv")
girl_names <- read_csv("https://raw.githubusercontent.com/maelle/za_babynames/master/data-raw/girls_names.csv")

girl_names$sex <- "female"
boy_names$sex <- "male"

sa_names <- rbind(girl_names, boy_names)

names(sa_names) <- c("first_name", "number", "sex")

use_data(sa_names, overwrite = TRUE)

use_r("za_names")
document()
```

# give name function()

```{r}
use_r("give_name")
load_all()
give_name("male")
use_test("give_name.R")

document()
devtools::test()
devtools::check()
```

# TRavis

```{r}
use_travis()
use_readme_md()
```

# test coverage

```{r}
use_coverage(type = "codecov")
```

# Github links

```{r}
use_github_links()
```

